import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Check, X } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { useDashboardStore } from "../../store/dashboardStore";

export function OnboardingTour() {
  const dismissed = useDashboardStore((state) => state.onboardingDismissed);
  const setDismissed = useDashboardStore((state) => state.setOnboardingDismissed);
  const navigate = useNavigate();
  const location = useLocation();
  const [stepIndex, setStepIndex] = useState(0);

  const steps = useMemo(
    () => [
      {
        route: "/",
        target: "kpis",
        title: "Hotspot intelligence",
        body: "Hotspots are clustered enforcement zones generated by the validated pipeline. The KPIs show the scale of observed violations, high-impact zones, emerging activity, and commercial corridor relevance.",
      },
      {
        route: "/workspace",
        target: "filters",
        title: "Impact score interpretation",
        body: "The impact score is the preserved model output. Filters change what is visible in the map, tables, charts, and exports without recalculating the model.",
      },
      {
        route: "/workspace",
        target: "map",
        title: "Operational map",
        body: "The map uses OpenStreetMap with clustering, heat, corridor, emerging, and high-priority overlays. Marker rings indicate confidence tier.",
      },
      {
        route: "/workspace",
        target: "details",
        title: "Enforcement priority",
        body: "Zone details expose score contribution, confidence, patrol window, commercial influence, and rising-status signals for deployment decisions.",
      },
    ],
    [],
  );

  const step = steps[stepIndex];

  useEffect(() => {
    if (dismissed) return;
    if (location.pathname !== step.route) {
      navigate(step.route, { replace: false });
      return;
    }
    window.setTimeout(() => {
      document.querySelector(`[data-tour="${step.target}"]`)?.scrollIntoView({ block: "center", behavior: "smooth" });
    }, 120);
  }, [dismissed, location.pathname, navigate, step.route, step.target]);

  if (dismissed) return null;

  function finish() {
    setDismissed(true);
  }

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-[1200] bg-zinc-950/45 p-4 backdrop-blur-[2px]"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <div className="flex min-h-full items-end justify-center sm:items-center">
          <motion.div
            role="dialog"
            aria-modal="true"
            aria-labelledby="onboarding-title"
            initial={{ opacity: 0, y: 18, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 18, scale: 0.98 }}
            className="w-full max-w-lg rounded-lg border border-zinc-200 bg-white p-5 shadow-panel"
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                  Product tour {stepIndex + 1} / {steps.length}
                </div>
                <h2 id="onboarding-title" className="mt-2 text-xl font-bold text-zinc-950">
                  {step.title}
                </h2>
              </div>
              <button
                type="button"
                aria-label="Close onboarding"
                onClick={finish}
                className="inline-flex h-8 w-8 items-center justify-center rounded-md text-zinc-500 hover:bg-zinc-100"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            <p className="mt-3 text-sm leading-6 text-zinc-600">{step.body}</p>
            <div className="mt-5 flex items-center justify-between gap-3">
              <div className="flex gap-1.5">
                {steps.map((item, index) => (
                  <span key={item.title} className={`h-1.5 w-8 rounded-full ${index <= stepIndex ? "bg-blue-600" : "bg-zinc-200"}`} />
                ))}
              </div>
              {stepIndex === steps.length - 1 ? (
                <button
                  type="button"
                  onClick={finish}
                  className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <Check className="h-4 w-4" />
                  Finish
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => setStepIndex((index) => index + 1)}
                  className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  Next
                  <ArrowRight className="h-4 w-4" />
                </button>
              )}
            </div>
          </motion.div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
